[package]
name = "callys-client"
version = "0.2.0"
edition = "2021"

[lib]
name = "callys_client"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "callys-client"
path = "src/main.rs"
required-features = ["desktop"]

[features]
default = []
desktop = []
android = []

[dependencies]
callys-asset = { path = "../asset" }
callys-core = { path = "../core" }
image = { version = "0.25.10", default-features = false, features = ["png"] }
sdl2 = { version = "0.37", features = ["image"], optional = true }

[target.'cfg(target_os = "android")'.dependencies]
