//! obj_laser (80) pickup: Create CODE 400 / Step CODE 401, the same two-event
//! shape as the verified shotgun/rifle/rocket/ice/spike pickups. Beacon
//! offset here is (x+0, y-16) — flatter than the other five. First laser
//! pickup of the post-Boss3 branch, sitting in asset room 76 (gml room77);
//! closes one name from weapons3-pickup-chain.md's outstanding list.
use callys_asset::GameDroidAsset;
use callys_core::code_vm::{load_bundle_from_file, Host};
use callys_core::ir_scene::{Scene, SpriteBounds};
use std::path::Path;
const P:i32=0;const W:i32=69;const PICKUPFLARE:i32=70;const LASER:i32=80;const FOUNDWEAPON:i32=82;
const WEAPONS:[&str;12]=["pistol","shotgun","assaultrifle","rocket","laser","icegun","bladegun","flamethrower","bow","bombgun","boomerang","spikegun"];
fn setup()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let r=Path::new(env!("CARGO_MANIFEST_DIR"));let a=GameDroidAsset::parse(r.join("../../assets/game.droid")).unwrap();let mut b=load_bundle_from_file(&r.join("src/generated/full_ir.json")).unwrap();b.string_table=a.string_table.clone();let mut s=Scene::default();s.init_bundle(&b);s.init_fresh_start_globals();for(sid,sp)in&a.sprites{s.sprite_bounds.insert(*sid as i32,SpriteBounds{width:sp.width as f64,height:sp.height as f64,origin_x:sp.origin_x as f64,origin_y:sp.origin_y as f64,frames:sp.tpag_indices.len().max(1)as f64});}s.load_room_from_data(&b,0,&a.rooms[0]).unwrap();s.transition_to_room(&b,1,&a.rooms[1]).unwrap();s.view_positions.insert(0,(0.,0.));let p=s.instances.iter().find(|(_,i)|i.object==P&&i.alive).map(|(id,_)|*id).unwrap();(b,s,p,a)}
fn walk(b:&callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,w:f64){let id=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive&&i.active).find(|(_,i)|i.fields.get("warproom").copied()==Some(w)).map(|(id,_)|*id).unwrap();let(x,y)=(s.instances[&id].fields["x"],s.instances[&id].fields["y"]);s.write(p,-1,"x",None,x).unwrap();s.write(p,-1,"y",None,y).unwrap();for _ in 0..3{s.tick(b).unwrap();if s.target_room_warp.is_some(){break}}let t=s.target_room_warp.take().unwrap();s.transition_to_room(b,t,&a.rooms[t]).unwrap()}
fn cast(s:&Scene,o:i32)->Vec<i32>{s.instances.iter().filter(|(_,i)|i.object==o&&i.alive).map(|(id,_)|*id).collect()}
fn active(s:&Scene)->Vec<String>{WEAPONS.iter().filter(|w|s.globals.get(**w).copied()==Some(1.)).map(|w|(*w).to_string()).collect()}
fn reach(b:&mut callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,target:f64){s.transition_to_room(b,4,&a.rooms[4]).unwrap();for w in (5i32..=target as i32).filter(|x|*x!=6).map(|x|x as f64){walk(b,s,a,p,w)}}
fn collect(b:&callys_core::code_vm::Bundle,s:&mut Scene,p:i32,pickup:i32){let(px,py)=(s.instances[&pickup].fields["x"],s.instances[&pickup].fields["y"]);s.write(p,-1,"x",None,px).unwrap();s.write(p,-1,"y",None,py).unwrap();for _ in 0..4{s.tick(b).unwrap();if !s.instances[&pickup].alive{break}}assert!(!s.instances[&pickup].alive,"the Step code destroys the pickup on contact")}
#[test]fn the_laser_pickup_flips_the_weapon_row(){let(mut b,mut s,p,a)=setup();reach(&mut b,&mut s,&a,p,76.);assert_eq!(s.current_room,76.,"asset76 = gml room77");let gun=*cast(&s,LASER).first().expect("one laser pickup in asset room 76");let flare=cast(&s,PICKUPFLARE);assert_eq!(flare.len(),1,"CODE 400 spawns exactly one beacon");assert_eq!(s.instances[&flare[0]].fields["x"],s.instances[&gun].fields["x"],"laser beacon keeps the pickup x");assert_eq!(s.instances[&flare[0]].fields["y"],s.instances[&gun].fields["y"]-16.,"laser beacon y offset -16, flatter than the other five guns");let(sx,sy)=(s.instances[&gun].fields["x"],s.instances[&gun].fields["y"]);assert_eq!(active(&s),vec!["pistol".to_string()],"fresh-start row is pistol only");collect(&b,&mut s,p,gun);assert_eq!(s.globals["laserbought"],1.,"CODE 401 raises laserbought");assert_eq!(active(&s),vec!["laser".to_string()],"exactly the laser stays active, the other eleven are zeroed");let banner=*cast(&s,FOUNDWEAPON).first().expect("banner");assert_eq!((s.instances[&banner].fields["x"],s.instances[&banner].fields["y"]),(sx,sy),"banner spawns on the pickup coordinates")}
#[test]
fn a_bought_laser_vanishes_on_room_reentry(){let(mut b,mut s,p,a)=setup();s.globals.insert("laserbought".to_string(),1.0);reach(&mut b,&mut s,&a,p,76.);assert_eq!(s.current_room,76.);assert!(cast(&s,LASER).is_empty(),"CODE 400 destroys the pickup before leaving a beacon");assert!(cast(&s,PICKUPFLARE).is_empty(),"no beacon either for an owned weapon");assert_eq!(active(&s),vec!["pistol".to_string()],"the destroy path must not flip the weapon row")}