//! room56-59 (asset rooms 54-57) post-Boss3 branch chain, tenth segment.
//! gml names via room_bindings: asset54=room56, asset55=room57, asset56=room58,
//! asset57=room59 (offset +3 verified). Every count and pin below was probed
//! live on this host from the real bytecode before freezing.
use callys_asset::GameDroidAsset;
use callys_core::code_vm::{load_bundle_from_file, Host};
use callys_core::ir_scene::{Scene, SpriteBounds};
use std::path::Path;
const P:i32=0;const W:i32=69;const WALL4:i32=4;const WALL5:i32=5;const BOULDER:i32=6;const PLATFORM:i32=7;const KNIFE:i32=15;const SKELETON:i32=17;const FIREHULK:i32=18;const ZOMBIE:i32=19;const SHOOTER2:i32=20;const HULK:i32=21;const ENEMY2:i32=22;const WOLF:i32=23;const GHOST:i32=24;const BAT:i32=31;const FIRE:i32=33;const COIN:i32=58;const GEM:i32=59;const CHEST:i32=100;const SWAP:i32=126;const BBLOCK:i32=156;
fn setup()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let r=Path::new(env!("CARGO_MANIFEST_DIR"));let a=GameDroidAsset::parse(r.join("../../assets/game.droid")).unwrap();let mut b=load_bundle_from_file(&r.join("src/generated/full_ir.json")).unwrap();b.string_table=a.string_table.clone();let mut s=Scene::default();s.init_bundle(&b);s.init_fresh_start_globals();for(sid,sp)in&a.sprites{s.sprite_bounds.insert(*sid as i32,SpriteBounds{width:sp.width as f64,height:sp.height as f64,origin_x:sp.origin_x as f64,origin_y:sp.origin_y as f64,frames:sp.tpag_indices.len().max(1)as f64});}s.load_room_from_data(&b,0,&a.rooms[0]).unwrap();s.transition_to_room(&b,1,&a.rooms[1]).unwrap();s.view_positions.insert(0,(0.,0.));let p=s.instances.iter().find(|(_,i)|i.object==P&&i.alive).map(|(id,_)|*id).unwrap();(b,s,p,a)}
fn walk(b:&callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,w:f64){let id=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive&&i.active).find(|(_,i)|i.fields.get("warproom").copied()==Some(w)).map(|(id,_)|*id).unwrap();let(x,y)=(s.instances[&id].fields["x"],s.instances[&id].fields["y"]);s.write(p,-1,"x",None,x).unwrap();s.write(p,-1,"y",None,y).unwrap();for _ in 0..3{s.tick(b).unwrap();if s.target_room_warp.is_some(){break}}let t=s.target_room_warp.take().unwrap();s.transition_to_room(b,t,&a.rooms[t]).unwrap()}
fn cast(s:&Scene,o:i32)->usize{s.instances.iter().filter(|(_,i)|i.object==o&&i.alive).count()}fn doors(s:&Scene)->Vec<(f64,f64,f64)>{s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).map(|(_,i)|(i.fields["warproom"],i.fields["warpx"],i.fields["warpy"])).collect()}
/// Every warp pin in this segment's creation CODE (910-919) stores
/// `other.unlocked = 1`; the test host must observe that on live instances.
fn assert_all_doors_unlocked(s:&Scene,room:f64){let live:Vec<_>=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).collect();assert_eq!(live.len(),2,"exactly two warp pins in asset room {room}");for (_,i) in &live{assert_eq!(i.fields.get("unlocked").copied(),Some(1.),"CODE 91x pins unlocked=1 on both doors of asset room {room}");}}
fn reach53()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let(b,mut s,p,a)=setup();s.transition_to_room(&b,4,&a.rooms[4]).unwrap();for w in (5i32..=53).filter(|x|*x!=6).map(|x|x as f64){walk(&b,&mut s,&a,p,w)}(b,s,p,a)}
#[test]fn room56_mixed_pressure_room_is_asset_exact(){let(b,mut s,p,a)=reach53();walk(&b,&mut s,&a,p,54.);assert_eq!(s.current_room,54.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,140.),"CODE 910 landing");assert_eq!(cast(&s,WALL4),146);assert_eq!(cast(&s,WALL5),211);assert_eq!(cast(&s,BOULDER),180);assert_eq!(cast(&s,SHOOTER2),2);assert_eq!(cast(&s,FIREHULK),1);assert_eq!(cast(&s,HULK),1);assert_eq!(cast(&s,ENEMY2),1);assert_eq!(cast(&s,WOLF),1);assert_eq!(cast(&s,BAT),3);assert_eq!(cast(&s,COIN),28);assert_eq!(cast(&s,GEM),3);assert_eq!(cast(&s,CHEST),1);assert_eq!(cast(&s,SWAP),1);assert_eq!(cast(&s,BBLOCK),0,"no boulderblocks in asset54");assert!(doors(&s).contains(&(53.,640.,684.)),"CODE 912 return pin to asset53");assert!(doors(&s).contains(&(55.,608.,556.)),"CODE 913 forward pin to asset55");assert_all_doors_unlocked(&s,54.);}
#[test]fn room57_boulderblock_gorge_is_asset_exact(){let(b,mut s,p,a)=reach53();walk(&b,&mut s,&a,p,54.);walk(&b,&mut s,&a,p,55.);assert_eq!(s.current_room,55.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(608.,556.),"CODE 913 landing");assert_eq!(cast(&s,WALL4),234);assert_eq!(cast(&s,WALL5),355);assert_eq!(cast(&s,BOULDER),209);assert_eq!(cast(&s,PLATFORM),2);assert_eq!(cast(&s,FIREHULK),2);assert_eq!(cast(&s,HULK),1);assert_eq!(cast(&s,ENEMY2),2);assert_eq!(cast(&s,GHOST),2);assert_eq!(cast(&s,BAT),1);assert_eq!(cast(&s,FIRE),1);assert_eq!(cast(&s,COIN),14);assert_eq!(cast(&s,CHEST),3);assert_eq!(cast(&s,BBLOCK),3,"the gorge's rocket-farm boulderblocks");assert!(doors(&s).contains(&(54.,640.,1164.)),"CODE 914 return pin");assert!(doors(&s).contains(&(56.,128.,300.)),"CODE 915 forward pin");assert_all_doors_unlocked(&s,55.);}
#[test]fn room58_zombie_hollow_is_asset_exact(){let(b,mut s,p,a)=reach53();walk(&b,&mut s,&a,p,54.);walk(&b,&mut s,&a,p,55.);walk(&b,&mut s,&a,p,56.);assert_eq!(s.current_room,56.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,300.),"CODE 915 landing");assert_eq!(cast(&s,WALL4),222);assert_eq!(cast(&s,WALL5),333);assert_eq!(cast(&s,BOULDER),226);assert_eq!(cast(&s,PLATFORM),2);assert_eq!(cast(&s,SKELETON),2);assert_eq!(cast(&s,ZOMBIE),5);assert_eq!(cast(&s,HULK),1);assert_eq!(cast(&s,BAT),2);assert_eq!(cast(&s,COIN),21);assert_eq!(cast(&s,CHEST),0,"no treasure in the hollow");assert_eq!(cast(&s,GEM),0);assert!(doors(&s).contains(&(55.,1376.,908.)),"CODE 916 return pin");assert!(doors(&s).contains(&(57.,128.,364.)),"CODE 917 forward pin");assert_all_doors_unlocked(&s,56.);}
#[test]fn room59_bat_nursery_and_full_return_chain(){let(b,mut s,p,a)=reach53();walk(&b,&mut s,&a,p,54.);walk(&b,&mut s,&a,p,55.);walk(&b,&mut s,&a,p,56.);walk(&b,&mut s,&a,p,57.);assert_eq!(s.current_room,57.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,364.),"CODE 917 landing");assert_eq!(cast(&s,WALL4),61);assert_eq!(cast(&s,WALL5),157);assert_eq!(cast(&s,BOULDER),46);assert_eq!(cast(&s,ZOMBIE),4);assert_eq!(cast(&s,BAT),5);assert_eq!(cast(&s,COIN),34);assert_eq!(cast(&s,CHEST),0);assert!(doors(&s).contains(&(56.,1920.,268.)),"CODE 918 return pin");assert!(doors(&s).contains(&(58.,128.,204.)),"CODE 919 forward pin continues to asset58");assert_all_doors_unlocked(&s,57.);
// the whole eighth segment walks back unchanged:
walk(&b,&mut s,&a,p,56.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1920.,268.),"CODE 918 landing back in asset56");walk(&b,&mut s,&a,p,55.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1376.,908.),"CODE 916 landing back in asset55");walk(&b,&mut s,&a,p,54.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(640.,1164.),"CODE 914 landing back in asset54");walk(&b,&mut s,&a,p,53.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(640.,684.),"CODE 912 landing back in asset53 (room55)");assert_eq!(s.current_room,53.);}
