//! room50 / rm_boss3 / room51 (asset rooms 47-49) post-Boss2 branch chain, eighth segment.
//! gml names via room_bindings: asset47=room50, asset48=rm_boss3, asset49=room51.
use callys_asset::GameDroidAsset;
use callys_core::code_vm::{load_bundle_from_file, Host};
use callys_core::ir_scene::{Scene, SpriteBounds};
use std::path::Path;
const P:i32=0;const W:i32=69;const BOSSBOULDER:i32=3;const WALL4:i32=4;const WALL5:i32=5;const BOULDER:i32=6;const PLATFORM:i32=7;const WATER:i32=9;const ENEMY:i32=14;const FIREHULK:i32=18;const ZOMBIE:i32=19;const SHOOTER2:i32=20;const HULK:i32=21;const ENEMY2:i32=22;const WOLF:i32=23;const GHOST:i32=24;const SLIME:i32=32;const BOSS3:i32=27;const COIN:i32=58;const CHEST:i32=100;const BBLOCK:i32=156;const ICEBLOCK:i32=159;const TRIGGERINTRO:i32=186;
fn setup()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let r=Path::new(env!("CARGO_MANIFEST_DIR"));let a=GameDroidAsset::parse(r.join("../../assets/game.droid")).unwrap();let mut b=load_bundle_from_file(&r.join("src/generated/full_ir.json")).unwrap();b.string_table=a.string_table.clone();let mut s=Scene::default();s.init_bundle(&b);s.init_fresh_start_globals();for(sid,sp)in&a.sprites{s.sprite_bounds.insert(*sid as i32,SpriteBounds{width:sp.width as f64,height:sp.height as f64,origin_x:sp.origin_x as f64,origin_y:sp.origin_y as f64,frames:sp.tpag_indices.len().max(1)as f64});}s.load_room_from_data(&b,0,&a.rooms[0]).unwrap();s.transition_to_room(&b,1,&a.rooms[1]).unwrap();s.view_positions.insert(0,(0.,0.));let p=s.instances.iter().find(|(_,i)|i.object==P&&i.alive).map(|(id,_)|*id).unwrap();(b,s,p,a)}
fn walk(b:&callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,w:f64){let id=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive&&i.active).find(|(_,i)|i.fields.get("warproom").copied()==Some(w)).map(|(id,_)|*id).unwrap();let(x,y)=(s.instances[&id].fields["x"],s.instances[&id].fields["y"]);s.write(p,-1,"x",None,x).unwrap();s.write(p,-1,"y",None,y).unwrap();for _ in 0..3{s.tick(b).unwrap();if s.target_room_warp.is_some(){break}}let t=s.target_room_warp.take().unwrap();s.transition_to_room(b,t,&a.rooms[t]).unwrap()}
fn cast(s:&Scene,o:i32)->usize{s.instances.iter().filter(|(_,i)|i.object==o&&i.alive).count()}fn doors(s:&Scene)->Vec<(f64,f64,f64)>{s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).map(|(_,i)|(i.fields["warproom"],i.fields["warpx"],i.fields["warpy"])).collect()}
fn reach47()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let(b,mut s,p,a)=setup();s.transition_to_room(&b,4,&a.rooms[4]).unwrap();for w in [5.,7.,8.,9.,10.,11.,12.,13.,14.,15.,16.,17.,18.,19.,20.,21.,22.,23.,24.,25.,26.,27.,28.,29.,30.,31.,32.,33.,34.,35.,36.,37.,38.,39.,40.,41.,42.,43.,44.,45.,46.,47.]{walk(&b,&mut s,&a,p,w)}(b,s,p,a)}
#[test]fn room50_boss3_gate_room_is_asset_exact(){let(b,mut s,p,a)=reach47();assert_eq!(s.current_room,47.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,140.));assert_eq!(cast(&s,WALL4),221);assert_eq!(cast(&s,WALL5),217);assert_eq!(cast(&s,BOULDER),245);assert_eq!(cast(&s,PLATFORM),8);assert_eq!(cast(&s,ENEMY),1);assert_eq!(cast(&s,ZOMBIE),2);assert_eq!(cast(&s,SHOOTER2),1);assert_eq!(cast(&s,HULK),3);assert_eq!(cast(&s,WOLF),1);assert_eq!(cast(&s,GHOST),1);assert_eq!(cast(&s,SLIME),2);assert_eq!(cast(&s,CHEST),5);assert_eq!(cast(&s,COIN),40);assert_eq!(cast(&s,BBLOCK),2);assert!(doors(&s).contains(&(48.,128.,108.)));assert!(doors(&s).contains(&(46.,512.,908.)));walk(&b,&mut s,&a,p,48.);assert_eq!(s.current_room,48.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,108.))}
#[test]fn rm_boss3_room_is_asset_exact(){let(b,mut s,p,a)=reach47();walk(&b,&mut s,&a,p,48.);assert_eq!(cast(&s,BOSS3),1);assert_eq!(cast(&s,BOSSBOULDER),18);assert_eq!(cast(&s,TRIGGERINTRO),1);assert_eq!(cast(&s,WALL4),76);assert_eq!(cast(&s,WALL5),182);assert_eq!(cast(&s,BOULDER),85);assert_eq!(cast(&s,COIN),0);assert_eq!(cast(&s,CHEST),0);assert!(doors(&s).contains(&(47.,992.,620.)));assert!(doors(&s).contains(&(49.,128.,300.)));walk(&b,&mut s,&a,p,49.);assert_eq!(s.current_room,49.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,300.))}
#[test]fn room51_ice_firehulk_room_is_asset_exact(){let(b,mut s,p,a)=reach47();walk(&b,&mut s,&a,p,48.);walk(&b,&mut s,&a,p,49.);assert_eq!(cast(&s,WALL4),201);assert_eq!(cast(&s,WALL5),318);assert_eq!(cast(&s,BOULDER),179);assert_eq!(cast(&s,PLATFORM),2);assert_eq!(cast(&s,WATER),24);assert_eq!(cast(&s,FIREHULK),2);assert_eq!(cast(&s,ZOMBIE),1);assert_eq!(cast(&s,ENEMY2),1);assert_eq!(cast(&s,SLIME),2);assert_eq!(cast(&s,CHEST),7);assert_eq!(cast(&s,COIN),28);assert_eq!(cast(&s,ICEBLOCK),3);assert_eq!(cast(&s,TRIGGERINTRO),1);assert!(doors(&s).contains(&(48.,1152.,364.)));assert!(doors(&s).contains(&(50.,128.,268.)))}

