//! room64-67 (asset rooms 62-66, rm_boss4 interrupting) post-Boss3 branch
//! chain, twelfth segment. gml names via room_bindings: asset62=room64,
//! asset63=room65, asset64=rm_boss4, asset65=room66, asset66=room67 (+3
//! offset, sixth confirmation; the boss-room interrupt is the same shape as
//! asset48=rm_boss3 in the eighth segment). Door CODEs 928-937 verified at
//! bytecode level; casts and landing pins probed live on this host first.
use callys_asset::GameDroidAsset;
use callys_core::code_vm::{load_bundle_from_file, Host};
use callys_core::ir_scene::{Scene, SpriteBounds};
use std::path::Path;
const P:i32=0;const W:i32=69;const WALL4:i32=4;const WALL5:i32=5;const BOULDER:i32=6;const PLATFORM:i32=7;const SPIKE:i32=8;const WATERSURFACE:i32=9;const WATERFILL:i32=10;const ENEMY:i32=14;const KNIFE:i32=15;const SHOOTER1:i32=16;const SKELETON:i32=17;const FIREHULK:i32=18;const ZOMBIE:i32=19;const SHOOTER2:i32=20;const HULK:i32=21;const ENEMY2:i32=22;const WOLF:i32=23;const GHOST:i32=24;const BOSS4:i32=28;const SLIME:i32=32;const FIRE:i32=33;const BOULDERBOSS:i32=3;const COIN:i32=58;const CHEST:i32=100;const FLAMETHROWER:i32=77;const ICEBLOCK:i32=159;const TRIGGERINTRO:i32=186;
fn setup()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let r=Path::new(env!("CARGO_MANIFEST_DIR"));let a=GameDroidAsset::parse(r.join("../../assets/game.droid")).unwrap();let mut b=load_bundle_from_file(&r.join("src/generated/full_ir.json")).unwrap();b.string_table=a.string_table.clone();let mut s=Scene::default();s.init_bundle(&b);s.init_fresh_start_globals();for(sid,sp)in&a.sprites{s.sprite_bounds.insert(*sid as i32,SpriteBounds{width:sp.width as f64,height:sp.height as f64,origin_x:sp.origin_x as f64,origin_y:sp.origin_y as f64,frames:sp.tpag_indices.len().max(1)as f64});}s.load_room_from_data(&b,0,&a.rooms[0]).unwrap();s.transition_to_room(&b,1,&a.rooms[1]).unwrap();s.view_positions.insert(0,(0.,0.));let p=s.instances.iter().find(|(_,i)|i.object==P&&i.alive).map(|(id,_)|*id).unwrap();(b,s,p,a)}
fn walk(b:&callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,w:f64){let id=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive&&i.active).find(|(_,i)|i.fields.get("warproom").copied()==Some(w)).map(|(id,_)|*id).unwrap();let(x,y)=(s.instances[&id].fields["x"],s.instances[&id].fields["y"]);s.write(p,-1,"x",None,x).unwrap();s.write(p,-1,"y",None,y).unwrap();for _ in 0..3{s.tick(b).unwrap();if s.target_room_warp.is_some(){break}}let t=s.target_room_warp.take().unwrap();s.transition_to_room(b,t,&a.rooms[t]).unwrap()}
fn cast(s:&Scene,o:i32)->usize{s.instances.iter().filter(|(_,i)|i.object==o&&i.alive).count()}fn doors(s:&Scene)->Vec<(f64,f64,f64)>{s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).map(|(_,i)|(i.fields["warproom"],i.fields["warpx"],i.fields["warpy"])).collect()}
fn assert_all_doors_unlocked(s:&Scene,room:f64){let live:Vec<_>=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).collect();assert_eq!(live.len(),2,"exactly two warp pins in asset room {room}");for (_,i) in &live{assert_eq!(i.fields.get("unlocked").copied(),Some(1.),"CODE 92x-93x pins unlocked=1 on both doors of asset room {room}");}}
fn reach61()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let(b,mut s,p,a)=setup();s.transition_to_room(&b,4,&a.rooms[4]).unwrap();for w in (5i32..=61).filter(|x|*x!=6).map(|x|x as f64){walk(&b,&mut s,&a,p,w)}(b,s,p,a)}
#[test]fn room64_mixed_gauntlet_is_asset_exact(){let(b,mut s,p,a)=reach61();walk(&b,&mut s,&a,p,62.);assert_eq!(s.current_room,62.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1664.,620.),"CODE 927 landing");assert_eq!(cast(&s,WALL4),275);assert_eq!(cast(&s,WALL5),213);assert_eq!(cast(&s,BOULDER),250);assert_eq!(cast(&s,PLATFORM),10,"platform-dense gauntlet, most in the branch");assert_eq!(cast(&s,KNIFE),2);assert_eq!(cast(&s,SHOOTER1),1);assert_eq!(cast(&s,SKELETON),1);assert_eq!(cast(&s,HULK),2);assert_eq!(cast(&s,ENEMY2),2);assert_eq!(cast(&s,WOLF),2);assert_eq!(cast(&s,SLIME),3);assert_eq!(cast(&s,COIN),21);assert_eq!(cast(&s,CHEST),0,"no treasure in the gauntlet");assert_eq!(cast(&s,ICEBLOCK),0);assert_eq!(cast(&s,FLAMETHROWER),0);assert!(doors(&s).contains(&(61.,128.,524.)),"CODE 928 return pin");assert!(doors(&s).contains(&(63.,128.,204.)),"CODE 929 forward pin");assert_all_doors_unlocked(&s,62.);}
#[test]fn room65_flamethrower_pickup_and_four_iceblocks(){let(b,mut s,p,a)=reach61();walk(&b,&mut s,&a,p,62.);walk(&b,&mut s,&a,p,63.);assert_eq!(s.current_room,63.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,204.),"CODE 929 landing");assert_eq!(cast(&s,WALL4),140);assert_eq!(cast(&s,WALL5),134);assert_eq!(cast(&s,BOULDER),189);assert_eq!(cast(&s,WATERSURFACE),11);assert_eq!(cast(&s,WATERFILL),3);assert_eq!(cast(&s,ENEMY),1);assert_eq!(cast(&s,SHOOTER1),1);assert_eq!(cast(&s,FIREHULK),1);assert_eq!(cast(&s,SHOOTER2),2);assert_eq!(cast(&s,ENEMY2),1);assert_eq!(cast(&s,WOLF),1);assert_eq!(cast(&s,COIN),31);assert_eq!(cast(&s,FLAMETHROWER),1,"first flamethrower pickup of the branch");assert_eq!(cast(&s,ICEBLOCK),4,"flamethrower room is also the densest iceblock room (melting pair)");assert_eq!(cast(&s,CHEST),0,"no treasure here");assert!(doors(&s).contains(&(62.,1920.,684.)),"CODE 930 return pin");assert!(doors(&s).contains(&(64.,128.,140.)),"CODE 931 forward pin into rm_boss4");assert_all_doors_unlocked(&s,63.);}
#[test]fn rm_boss4_arena_has_boss_boulders_and_intro_trigger(){let(b,mut s,p,a)=reach61();walk(&b,&mut s,&a,p,62.);walk(&b,&mut s,&a,p,63.);walk(&b,&mut s,&a,p,64.);assert_eq!(s.current_room,64.,"asset64 = gml rm_boss4, +3 offset with boss interrupt");assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,140.),"CODE 931 landing");assert_eq!(cast(&s,BOSS4),1,"obj_boss4 sprite 76");assert_eq!(cast(&s,BOULDERBOSS),2,"two obj_bossboulder (CODE 28/29)");assert_eq!(cast(&s,TRIGGERINTRO),1,"obj_triggerintro gates the intro");assert_eq!(cast(&s,WALL4),75);assert_eq!(cast(&s,WALL5),208);assert_eq!(cast(&s,BOULDER),89);assert_eq!(cast(&s,PLATFORM),1);assert_eq!(cast(&s,COIN),0,"clean boss arena, no loot");assert_eq!(cast(&s,SHOOTER1)+cast(&s,SHOOTER2)+cast(&s,SLIME)+cast(&s,WOLF),0,"no mob trash in the arena");assert!(doors(&s).contains(&(63.,2432.,236.)),"CODE 932 return pin");assert!(doors(&s).contains(&(65.,128.,108.)),"CODE 933 forward pin");assert_all_doors_unlocked(&s,64.);}
#[test]fn room66_iceblock_shelf_and_single_chest(){let(b,mut s,p,a)=reach61();walk(&b,&mut s,&a,p,62.);walk(&b,&mut s,&a,p,63.);walk(&b,&mut s,&a,p,64.);walk(&b,&mut s,&a,p,65.);assert_eq!(s.current_room,65.,"asset65 = gml room66 (rm_boss4 broke the run)");assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,108.),"CODE 933 landing");assert_eq!(cast(&s,WALL4),85);assert_eq!(cast(&s,WALL5),125);assert_eq!(cast(&s,BOULDER),139);assert_eq!(cast(&s,PLATFORM),5);assert_eq!(cast(&s,SHOOTER1),1);assert_eq!(cast(&s,FIREHULK),1);assert_eq!(cast(&s,SHOOTER2),1);assert_eq!(cast(&s,WOLF),1);assert_eq!(cast(&s,GHOST),2);assert_eq!(cast(&s,COIN),22);assert_eq!(cast(&s,CHEST),1);assert_eq!(cast(&s,ICEBLOCK),5,"most iceblocks in one room; melting contract applies");assert!(doors(&s).contains(&(64.,1152.,364.)),"CODE 934 return pin");assert!(doors(&s).contains(&(66.,128.,204.)),"CODE 935 forward pin");assert_all_doors_unlocked(&s,65.);}
#[test]fn room67_chest_hoard_and_full_return_chain(){let(b,mut s,p,a)=reach61();walk(&b,&mut s,&a,p,62.);walk(&b,&mut s,&a,p,63.);walk(&b,&mut s,&a,p,64.);walk(&b,&mut s,&a,p,65.);walk(&b,&mut s,&a,p,66.);assert_eq!(s.current_room,66.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,204.),"CODE 935 landing");assert_eq!(cast(&s,WALL4),283);assert_eq!(cast(&s,WALL5),159);assert_eq!(cast(&s,BOULDER),139);assert_eq!(cast(&s,SPIKE),10);assert_eq!(cast(&s,KNIFE),1);assert_eq!(cast(&s,SKELETON),1);assert_eq!(cast(&s,FIREHULK),2);assert_eq!(cast(&s,ZOMBIE),2);assert_eq!(cast(&s,SHOOTER2),2);assert_eq!(cast(&s,HULK),1);assert_eq!(cast(&s,WOLF),1);assert_eq!(cast(&s,SLIME),4);assert_eq!(cast(&s,FIRE),1);assert_eq!(cast(&s,COIN),32);assert_eq!(cast(&s,CHEST),6,"six-chest hoard, largest single-room chest count of the branch");assert_eq!(cast(&s,ICEBLOCK),2);assert!(doors(&s).contains(&(65.,352.,1164.)),"CODE 936 return pin");assert!(doors(&s).contains(&(67.,128.,108.)),"CODE 937 forward pin continues to asset67");assert_all_doors_unlocked(&s,66.);
walk(&b,&mut s,&a,p,65.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(352.,1164.),"CODE 936 landing back in asset65");walk(&b,&mut s,&a,p,64.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1152.,364.),"CODE 934 landing back in rm_boss4");walk(&b,&mut s,&a,p,63.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(2432.,236.),"CODE 932 landing back in asset63");walk(&b,&mut s,&a,p,62.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1920.,684.),"CODE 930 landing back in asset62");assert_eq!(s.current_room,62.);}
