//! room52-55 (asset rooms 50-53) post-Boss3 branch chain, ninth segment.
//! gml names via room_bindings: asset50=room52, asset51=room53, asset52=room54, asset53=room55.
use callys_asset::GameDroidAsset;
use callys_core::code_vm::{load_bundle_from_file, Host};
use callys_core::ir_scene::{Scene, SpriteBounds};
use std::path::Path;
const P:i32=0;const W:i32=69;const WALL4:i32=4;const WALL5:i32=5;const BOULDER:i32=6;const PLATFORM:i32=7;const SPIKE:i32=8;const KNIFE:i32=15;const SHOOTER1:i32=16;const SKELETON:i32=17;const FIREHULK:i32=18;const ZOMBIE:i32=19;const HULK:i32=21;const ENEMY2:i32=22;const WOLF:i32=23;const GHOST:i32=24;const BAT:i32=31;const SLIME:i32=32;const FIRE:i32=33;const COIN:i32=58;const GEM:i32=59;const FLARE:i32=70;const ICEGUN:i32=81;const SPIKEGUN:i32=72;const CHEST:i32=100;const LLOYD:i32=154;const BBLOCK:i32=156;const ICEBLOCK:i32=159;
fn setup()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let r=Path::new(env!("CARGO_MANIFEST_DIR"));let a=GameDroidAsset::parse(r.join("../../assets/game.droid")).unwrap();let mut b=load_bundle_from_file(&r.join("src/generated/full_ir.json")).unwrap();b.string_table=a.string_table.clone();let mut s=Scene::default();s.init_bundle(&b);s.init_fresh_start_globals();for(sid,sp)in&a.sprites{s.sprite_bounds.insert(*sid as i32,SpriteBounds{width:sp.width as f64,height:sp.height as f64,origin_x:sp.origin_x as f64,origin_y:sp.origin_y as f64,frames:sp.tpag_indices.len().max(1)as f64});}s.load_room_from_data(&b,0,&a.rooms[0]).unwrap();s.transition_to_room(&b,1,&a.rooms[1]).unwrap();s.view_positions.insert(0,(0.,0.));let p=s.instances.iter().find(|(_,i)|i.object==P&&i.alive).map(|(id,_)|*id).unwrap();(b,s,p,a)}
fn walk(b:&callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,w:f64){let id=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive&&i.active).find(|(_,i)|i.fields.get("warproom").copied()==Some(w)).map(|(id,_)|*id).unwrap();let(x,y)=(s.instances[&id].fields["x"],s.instances[&id].fields["y"]);s.write(p,-1,"x",None,x).unwrap();s.write(p,-1,"y",None,y).unwrap();for _ in 0..3{s.tick(b).unwrap();if s.target_room_warp.is_some(){break}}let t=s.target_room_warp.take().unwrap();s.transition_to_room(b,t,&a.rooms[t]).unwrap()}
fn cast(s:&Scene,o:i32)->usize{s.instances.iter().filter(|(_,i)|i.object==o&&i.alive).count()}fn doors(s:&Scene)->Vec<(f64,f64,f64)>{s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).map(|(_,i)|(i.fields["warproom"],i.fields["warpx"],i.fields["warpy"])).collect()}
fn reach49()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let(b,mut s,p,a)=setup();s.transition_to_room(&b,4,&a.rooms[4]).unwrap();for w in [5.,7.,8.,9.,10.,11.,12.,13.,14.,15.,16.,17.,18.,19.,20.,21.,22.,23.,24.,25.,26.,27.,28.,29.,30.,31.,32.,33.,34.,35.,36.,37.,38.,39.,40.,41.,42.,43.,44.,45.,46.,47.,48.,49.]{walk(&b,&mut s,&a,p,w)}(b,s,p,a)}
#[test]fn room52_boulder_field_is_asset_exact(){let(b,mut s,p,a)=reach49();assert_eq!(s.current_room,49.);walk(&b,&mut s,&a,p,50.);assert_eq!(s.current_room,50.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,268.));assert_eq!(cast(&s,WALL4),46);assert_eq!(cast(&s,WALL5),0);assert_eq!(cast(&s,BOULDER),260);assert_eq!(cast(&s,COIN),16);assert_eq!(cast(&s,CHEST),0);assert!(doors(&s).contains(&(49.,1920.,332.)));assert!(doors(&s).contains(&(51.,128.,140.)))}
#[test]fn room53_icegun_room_is_asset_exact(){let(b,mut s,p,a)=reach49();walk(&b,&mut s,&a,p,50.);walk(&b,&mut s,&a,p,51.);assert_eq!(s.current_room,51.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,140.));assert_eq!(cast(&s,WALL4),127);assert_eq!(cast(&s,WALL5),214);assert_eq!(cast(&s,BOULDER),226);assert_eq!(cast(&s,PLATFORM),14);assert_eq!(cast(&s,KNIFE),1);assert_eq!(cast(&s,SHOOTER1),1);assert_eq!(cast(&s,ZOMBIE),2);assert_eq!(cast(&s,GHOST),2);assert_eq!(cast(&s,BAT),2);assert_eq!(cast(&s,FIRE),2);assert_eq!(cast(&s,GEM),3);assert_eq!(cast(&s,FLARE),1);assert_eq!(cast(&s,ICEGUN),1);assert_eq!(cast(&s,COIN),15);assert_eq!(cast(&s,BBLOCK),3);assert!(doors(&s).contains(&(50.,640.,268.)));assert!(doors(&s).contains(&(52.,128.,204.)))}
#[test]fn room54_giant_wall_room_is_asset_exact(){let(b,mut s,p,a)=reach49();walk(&b,&mut s,&a,p,50.);walk(&b,&mut s,&a,p,51.);walk(&b,&mut s,&a,p,52.);assert_eq!(s.current_room,52.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,204.));assert_eq!(cast(&s,WALL4),434);assert_eq!(cast(&s,WALL5),579);assert_eq!(cast(&s,BOULDER),259);assert_eq!(cast(&s,SPIKE),16);assert_eq!(cast(&s,FIREHULK),2);assert_eq!(cast(&s,HULK),2);assert_eq!(cast(&s,KNIFE),1);assert_eq!(cast(&s,ENEMY2),1);assert_eq!(cast(&s,WOLF),1);assert_eq!(cast(&s,BAT),1);assert_eq!(cast(&s,SLIME),1);assert_eq!(cast(&s,CHEST),6);assert_eq!(cast(&s,COIN),13);assert_eq!(cast(&s,GEM),1);assert_eq!(cast(&s,ICEBLOCK),2);assert!(doors(&s).contains(&(51.,480.,1484.)));assert!(doors(&s).contains(&(53.,128.,204.)))}
#[test]fn room55_spikegun_room_is_asset_exact(){let(b,mut s,p,a)=reach49();walk(&b,&mut s,&a,p,50.);walk(&b,&mut s,&a,p,51.);walk(&b,&mut s,&a,p,52.);walk(&b,&mut s,&a,p,53.);assert_eq!(s.current_room,53.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,204.));assert_eq!(cast(&s,WALL4),77);assert_eq!(cast(&s,WALL5),53);assert_eq!(cast(&s,BOULDER),151);assert_eq!(cast(&s,SPIKE),14);assert_eq!(cast(&s,SKELETON),1);assert_eq!(cast(&s,HULK),1);assert_eq!(cast(&s,GHOST),1);assert_eq!(cast(&s,KNIFE),1);assert_eq!(cast(&s,LLOYD),1);assert_eq!(cast(&s,FLARE),1);assert_eq!(cast(&s,SPIKEGUN),1);assert_eq!(cast(&s,COIN),18);assert!(doors(&s).contains(&(52.,1760.,1164.)));assert!(doors(&s).contains(&(54.,128.,140.)))}
