//! room68-71 (asset rooms 67-70) post-Boss3 branch chain, thirteenth
//! segment. gml names via room_bindings: asset67=room68, asset68=room69,
//! asset69=room70, asset70=room71 (offset +1 after the rm_boss4 interrupt;
//! see room68-71-branch.md for the corrected rule). No boss
//! interrupt this segment. Door CODEs 938-945 verified at bytecode level;
//! casts and landing pins probed live on this host first.
use callys_asset::GameDroidAsset;
use callys_core::code_vm::{load_bundle_from_file, Host};
use callys_core::ir_scene::{Scene, SpriteBounds};
use std::path::Path;
const P:i32=0;const W:i32=69;const WALL4:i32=4;const WALL5:i32=5;const BOULDER:i32=6;const PLATFORM:i32=7;const SPIKE:i32=8;const WATERSURFACE:i32=9;const WATERFILL:i32=10;const ENEMY:i32=14;const SHOOTER1:i32=16;const SKELETON:i32=17;const FIREHULK:i32=18;const ZOMBIE:i32=19;const SHOOTER2:i32=20;const HULK:i32=21;const ENEMY2:i32=22;const GHOST:i32=24;const BAT:i32=31;const SLIME:i32=32;const FIRE:i32=33;const COIN:i32=58;const CHEST:i32=100;const BBLOCK:i32=156;const ICEBLOCK:i32=159;
fn setup()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let r=Path::new(env!("CARGO_MANIFEST_DIR"));let a=GameDroidAsset::parse(r.join("../../assets/game.droid")).unwrap();let mut b=load_bundle_from_file(&r.join("src/generated/full_ir.json")).unwrap();b.string_table=a.string_table.clone();let mut s=Scene::default();s.init_bundle(&b);s.init_fresh_start_globals();for(sid,sp)in&a.sprites{s.sprite_bounds.insert(*sid as i32,SpriteBounds{width:sp.width as f64,height:sp.height as f64,origin_x:sp.origin_x as f64,origin_y:sp.origin_y as f64,frames:sp.tpag_indices.len().max(1)as f64});}s.load_room_from_data(&b,0,&a.rooms[0]).unwrap();s.transition_to_room(&b,1,&a.rooms[1]).unwrap();s.view_positions.insert(0,(0.,0.));let p=s.instances.iter().find(|(_,i)|i.object==P&&i.alive).map(|(id,_)|*id).unwrap();(b,s,p,a)}
fn walk(b:&callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,w:f64){let id=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive&&i.active).find(|(_,i)|i.fields.get("warproom").copied()==Some(w)).map(|(id,_)|*id).unwrap();let(x,y)=(s.instances[&id].fields["x"],s.instances[&id].fields["y"]);s.write(p,-1,"x",None,x).unwrap();s.write(p,-1,"y",None,y).unwrap();for _ in 0..3{s.tick(b).unwrap();if s.target_room_warp.is_some(){break}}let t=s.target_room_warp.take().unwrap();s.transition_to_room(b,t,&a.rooms[t]).unwrap()}
fn cast(s:&Scene,o:i32)->usize{s.instances.iter().filter(|(_,i)|i.object==o&&i.alive).count()}fn doors(s:&Scene)->Vec<(f64,f64,f64)>{s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).map(|(_,i)|(i.fields["warproom"],i.fields["warpx"],i.fields["warpy"])).collect()}
fn assert_all_doors_unlocked(s:&Scene,room:f64){let live:Vec<_>=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).collect();assert_eq!(live.len(),2,"exactly two warp pins in asset room {room}");for (_,i) in &live{assert_eq!(i.fields.get("unlocked").copied(),Some(1.),"CODE 93x-94x pins unlocked=1 on both doors of asset room {room}");}}
fn reach66()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let(b,mut s,p,a)=setup();s.transition_to_room(&b,4,&a.rooms[4]).unwrap();for w in (5i32..=66).filter(|x|*x!=6).map(|x|x as f64){walk(&b,&mut s,&a,p,w)}(b,s,p,a)}
#[test]fn room68_ghost_gauntlet_is_asset_exact(){let(b,mut s,p,a)=reach66();walk(&b,&mut s,&a,p,67.);assert_eq!(s.current_room,67.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,108.),"CODE 937 landing");assert_eq!(cast(&s,WALL4),281);assert_eq!(cast(&s,WALL5),414,"wall_2-densest room of the branch");assert_eq!(cast(&s,BOULDER),176);assert_eq!(cast(&s,ENEMY),1);assert_eq!(cast(&s,SHOOTER1),1);assert_eq!(cast(&s,SKELETON),1);assert_eq!(cast(&s,FIREHULK),2);assert_eq!(cast(&s,HULK),2);assert_eq!(cast(&s,ENEMY2),1);assert_eq!(cast(&s,GHOST),1);assert_eq!(cast(&s,BAT),1);assert_eq!(cast(&s,COIN),27);assert_eq!(cast(&s,CHEST),0,"no treasure in the gauntlet");assert_eq!(cast(&s,ICEBLOCK),0);assert_eq!(cast(&s,SPIKE),0);assert_eq!(cast(&s,WATERSURFACE),0);assert!(doors(&s).contains(&(66.,1920.,268.)),"CODE 938 return pin");assert!(doors(&s).contains(&(68.,672.,364.)),"CODE 939 forward pin");assert_all_doors_unlocked(&s,67.);}
#[test]fn room69_ghost_nursery_and_two_chests(){let(b,mut s,p,a)=reach66();walk(&b,&mut s,&a,p,67.);walk(&b,&mut s,&a,p,68.);assert_eq!(s.current_room,68.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(672.,364.),"CODE 939 landing");assert_eq!(cast(&s,WALL4),58);assert_eq!(cast(&s,WALL5),77);assert_eq!(cast(&s,BOULDER),50);assert_eq!(cast(&s,FIREHULK),1);assert_eq!(cast(&s,GHOST),3,"ghost nursery, most ghosts per room so far");assert_eq!(cast(&s,COIN),3);assert_eq!(cast(&s,CHEST),2);assert_eq!(cast(&s,BAT),0,"ghosts are the only movers");assert_eq!(cast(&s,SLIME),0);assert!(doors(&s).contains(&(67.,128.,1164.)),"CODE 941 return pin");assert!(doors(&s).contains(&(69.,1920.,172.)),"CODE 940 forward pin");assert_all_doors_unlocked(&s,68.);}
#[test]fn room70_spike_fireslime_hoard(){let(b,mut s,p,a)=reach66();walk(&b,&mut s,&a,p,67.);walk(&b,&mut s,&a,p,68.);walk(&b,&mut s,&a,p,69.);assert_eq!(s.current_room,69.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1920.,172.),"CODE 940 landing");assert_eq!(cast(&s,WALL4),318);assert_eq!(cast(&s,WALL5),322);assert_eq!(cast(&s,BOULDER),170);assert_eq!(cast(&s,PLATFORM),5);assert_eq!(cast(&s,SPIKE),19);assert_eq!(cast(&s,SHOOTER1),1);assert_eq!(cast(&s,ZOMBIE),2);assert_eq!(cast(&s,HULK),3);assert_eq!(cast(&s,ENEMY2),1);assert_eq!(cast(&s,GHOST),1);assert_eq!(cast(&s,BAT),1);assert_eq!(cast(&s,SLIME),1);assert_eq!(cast(&s,FIRE),5,"fireslime den");assert_eq!(cast(&s,COIN),32);assert_eq!(cast(&s,CHEST),6,"second six-chest hoard of the chain");assert_eq!(cast(&s,BBLOCK),3,"fourth boulderblock room (rocket payoff)");assert_eq!(cast(&s,ICEBLOCK),0);assert!(doors(&s).contains(&(68.,128.,204.)),"CODE 943 return pin");assert!(doors(&s).contains(&(70.,128.,684.)),"CODE 942 forward pin");assert_all_doors_unlocked(&s,69.);}
#[test]fn room71_water_crossing_and_full_return_chain(){let(b,mut s,p,a)=reach66();walk(&b,&mut s,&a,p,67.);walk(&b,&mut s,&a,p,68.);walk(&b,&mut s,&a,p,69.);walk(&b,&mut s,&a,p,70.);assert_eq!(s.current_room,70.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,684.),"CODE 942 landing");assert_eq!(cast(&s,WALL4),65);assert_eq!(cast(&s,WALL5),52);assert_eq!(cast(&s,BOULDER),177);assert_eq!(cast(&s,WATERSURFACE),25);assert_eq!(cast(&s,WATERFILL),1);assert_eq!(cast(&s,SHOOTER1),1);assert_eq!(cast(&s,ZOMBIE),2);assert_eq!(cast(&s,SHOOTER2),1);assert_eq!(cast(&s,GHOST),1);assert_eq!(cast(&s,BAT),1);assert_eq!(cast(&s,COIN),20);assert_eq!(cast(&s,CHEST),0,"no treasure in the crossing");assert_eq!(cast(&s,SPIKE),0);assert!(doors(&s).contains(&(69.,1920.,620.)),"CODE 944 return pin");assert!(doors(&s).contains(&(71.,128.,192.)),"CODE 945 forward pin continues to asset71");assert_all_doors_unlocked(&s,70.);
walk(&b,&mut s,&a,p,69.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1920.,620.),"CODE 944 landing back in asset69");walk(&b,&mut s,&a,p,68.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,204.),"CODE 943 landing back in asset68");walk(&b,&mut s,&a,p,67.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,1164.),"CODE 941 landing back in asset67");walk(&b,&mut s,&a,p,66.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1920.,268.),"CODE 938 landing back in asset66");assert_eq!(s.current_room,66.);}
