//! room46-49 (asset rooms 43-46) post-Boss2 branch chain, seventh segment.
use callys_asset::GameDroidAsset;
use callys_core::code_vm::{load_bundle_from_file, Host};
use callys_core::ir_scene::{Scene, SpriteBounds};
use std::path::Path;
const P:i32=0;const W:i32=69;const WALL4:i32=4;const WALL5:i32=5;const SPIKE:i32=8;const WATER:i32=9;const ENEMY:i32=14;const KNIFE:i32=15;const SKELETON:i32=17;const ZOMBIE:i32=19;const HULK:i32=21;const ENEMY2:i32=22;const GHOST:i32=24;const BAT:i32=31;const SLIME:i32=32;const PLATFORM:i32=7;const BOULDER:i32=6;const COIN:i32=58;const FLARE:i32=70;const ROCKET:i32=75;const CHEST:i32=100;const LLOYD:i32=154;const BBLOCK:i32=156;
fn setup()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let r=Path::new(env!("CARGO_MANIFEST_DIR"));let a=GameDroidAsset::parse(r.join("../../assets/game.droid")).unwrap();let mut b=load_bundle_from_file(&r.join("src/generated/full_ir.json")).unwrap();b.string_table=a.string_table.clone();let mut s=Scene::default();s.init_bundle(&b);s.init_fresh_start_globals();for(sid,sp)in&a.sprites{s.sprite_bounds.insert(*sid as i32,SpriteBounds{width:sp.width as f64,height:sp.height as f64,origin_x:sp.origin_x as f64,origin_y:sp.origin_y as f64,frames:sp.tpag_indices.len().max(1)as f64});}s.load_room_from_data(&b,0,&a.rooms[0]).unwrap();s.transition_to_room(&b,1,&a.rooms[1]).unwrap();s.view_positions.insert(0,(0.,0.));let p=s.instances.iter().find(|(_,i)|i.object==P&&i.alive).map(|(id,_)|*id).unwrap();(b,s,p,a)}
fn walk(b:&callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,w:f64){let id=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive&&i.active).find(|(_,i)|i.fields.get("warproom").copied()==Some(w)).map(|(id,_)|*id).unwrap();let(x,y)=(s.instances[&id].fields["x"],s.instances[&id].fields["y"]);s.write(p,-1,"x",None,x).unwrap();s.write(p,-1,"y",None,y).unwrap();for _ in 0..3{s.tick(b).unwrap();if s.target_room_warp.is_some(){break}}let t=s.target_room_warp.take().unwrap();s.transition_to_room(b,t,&a.rooms[t]).unwrap()}
fn cast(s:&Scene,o:i32)->usize{s.instances.iter().filter(|(_,i)|i.object==o&&i.alive).count()}fn doors(s:&Scene)->Vec<(f64,f64,f64)>{s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).map(|(_,i)|(i.fields["warproom"],i.fields["warpx"],i.fields["warpy"])).collect()}
fn reach43()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let(b,mut s,p,a)=setup();s.transition_to_room(&b,4,&a.rooms[4]).unwrap();for w in [5.,7.,8.,9.,10.,11.,12.,13.,14.,15.,16.,17.,18.,19.,20.,21.,22.,23.,24.,25.,26.,27.,28.,29.,30.,31.,32.,33.,34.,35.,36.,37.,38.,39.,40.,41.,42.,43.] {walk(&b,&mut s,&a,p,w)}(b,s,p,a)}
#[test]fn room46_lloyd_room_is_asset_exact(){let(b,mut s,p,a)=reach43();assert_eq!(s.current_room,43.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(576.,204.));assert_eq!(cast(&s,LLOYD),1);assert_eq!(cast(&s,CHEST),3);assert_eq!(cast(&s,BOULDER),104);assert_eq!(cast(&s,WALL4),0);assert!(doors(&s).contains(&(44.,1120.,76.)));assert!(doors(&s).contains(&(42.,128.,524.)));walk(&b,&mut s,&a,p,44.);assert_eq!(s.current_room,44.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1120.,76.))}
#[test]fn room47_to_room48_is_asset_exact(){let(b,mut s,p,a)=reach43();walk(&b,&mut s,&a,p,44.);assert_eq!(cast(&s,WALL4),107);assert_eq!(cast(&s,WALL5),87);assert_eq!(cast(&s,BOULDER),112);assert_eq!(cast(&s,PLATFORM),8);assert_eq!(cast(&s,WATER),32);assert_eq!(cast(&s,ENEMY),1);assert_eq!(cast(&s,KNIFE),2);assert_eq!(cast(&s,SKELETON),1);assert_eq!(cast(&s,ZOMBIE),1);assert_eq!(cast(&s,ENEMY2),1);assert_eq!(cast(&s,BAT),1);assert_eq!(cast(&s,CHEST),3);assert_eq!(cast(&s,COIN),24);assert_eq!(cast(&s,BBLOCK),3);assert!(doors(&s).contains(&(45.,128.,204.)));assert!(doors(&s).contains(&(43.,128.,204.)));walk(&b,&mut s,&a,p,45.);assert_eq!(s.current_room,45.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,204.))}
#[test]fn room48_rocket_room_is_asset_exact(){let(b,mut s,p,a)=reach43();walk(&b,&mut s,&a,p,44.);walk(&b,&mut s,&a,p,45.);assert_eq!(cast(&s,WALL4),110);assert_eq!(cast(&s,WALL5),134);assert_eq!(cast(&s,BOULDER),323);assert_eq!(cast(&s,SPIKE),57);assert_eq!(cast(&s,KNIFE),2);assert_eq!(cast(&s,HULK),2);assert_eq!(cast(&s,GHOST),2);assert_eq!(cast(&s,SLIME),1);assert_eq!(cast(&s,FLARE),1);assert_eq!(cast(&s,ROCKET),1);assert_eq!(cast(&s,COIN),20);assert_eq!(cast(&s,BBLOCK),4);assert!(doors(&s).contains(&(44.,1152.,524.)));assert!(doors(&s).contains(&(46.,128.,108.)));walk(&b,&mut s,&a,p,46.);assert_eq!(s.current_room,46.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,108.))}
#[test]fn room49_to_room50_door_chain_continues(){let(b,mut s,p,a)=reach43();walk(&b,&mut s,&a,p,44.);walk(&b,&mut s,&a,p,45.);walk(&b,&mut s,&a,p,46.);assert_eq!(cast(&s,WALL4),43);assert_eq!(cast(&s,WALL5),10);assert_eq!(cast(&s,BOULDER),170);assert_eq!(cast(&s,WATER),12);assert_eq!(cast(&s,KNIFE),2);assert_eq!(cast(&s,HULK),1);assert_eq!(cast(&s,BAT),2);assert_eq!(cast(&s,CHEST),1);assert_eq!(cast(&s,COIN),12);assert_eq!(cast(&s,BBLOCK),2);assert!(doors(&s).contains(&(45.,1408.,684.)));assert!(doors(&s).contains(&(47.,128.,140.)))}
