//! room40-41 (asset rooms 37-38) post-Boss2 branch chain, fifth segment.
use callys_asset::GameDroidAsset;
use callys_core::code_vm::{load_bundle_from_file, Host};
use callys_core::ir_scene::{Scene, SpriteBounds};
use std::path::Path;

const PLAYER:i32=0; const WARP:i32=69; const KNIFEBANDIT:i32=15; const ZOMBIE:i32=19; const ENEMY2:i32=22; const GHOST:i32=24; const WOLF:i32=23; const BAT:i32=31; const SLIME:i32=32; const FIRESLIME:i32=33; const BOULDER:i32=6; const PLATFORM:i32=7; const SPIKES:i32=8; const COIN:i32=58; const GEM:i32=59; const CHEST:i32=100; const PICKUPFLARE:i32=70; const BOW:i32=78; const LLOYD:i32=154; const BOULDERBLOCK:i32=156; const TRIGGERINTRO:i32=186;
fn setup()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let r=Path::new(env!("CARGO_MANIFEST_DIR"));let a=GameDroidAsset::parse(r.join("../../assets/game.droid")).unwrap();let mut b=load_bundle_from_file(&r.join("src/generated/full_ir.json")).unwrap();b.string_table=a.string_table.clone();let mut s=Scene::default();s.init_bundle(&b);s.init_fresh_start_globals();for(sid,sp)in&a.sprites{s.sprite_bounds.insert(*sid as i32,SpriteBounds{width:sp.width as f64,height:sp.height as f64,origin_x:sp.origin_x as f64,origin_y:sp.origin_y as f64,frames:sp.tpag_indices.len().max(1)as f64});}s.load_room_from_data(&b,0,&a.rooms[0]).unwrap();s.transition_to_room(&b,1,&a.rooms[1]).unwrap();s.view_positions.insert(0,(0.0,0.0));let p=s.instances.iter().find(|(_,i)|i.object==PLAYER&&i.alive).map(|(id,_)|*id).unwrap();(b,s,p,a)}
fn walk(b:&callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,w:f64){let id=s.instances.iter().filter(|(_,i)|i.object==WARP&&i.alive&&i.active).find(|(_,i)|i.fields.get("warproom").copied()==Some(w)).map(|(id,_)|*id).unwrap();let(x,y)=(s.instances[&id].fields["x"],s.instances[&id].fields["y"]);s.write(p,-1,"x",None,x).unwrap();s.write(p,-1,"y",None,y).unwrap();for _ in 0..3{s.tick(b).unwrap();if s.target_room_warp.is_some(){break}}let t=s.target_room_warp.take().unwrap();s.transition_to_room(b,t,&a.rooms[t]).unwrap()}
fn cast(s:&Scene,o:i32)->usize{s.instances.iter().filter(|(_,i)|i.object==o&&i.alive).count()}
fn doors(s:&Scene)->Vec<(f64,f64,f64)>{s.instances.iter().filter(|(_,i)|i.object==WARP&&i.alive).map(|(_,i)|(i.fields["warproom"],i.fields["warpx"],i.fields["warpy"])).collect()}
fn reach_room37()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let(b,mut s,p,a)=setup();s.transition_to_room(&b,4,&a.rooms[4]).unwrap();for w in [5.,7.,8.,9.,10.,11.,12.,13.,14.,15.,16.,17.,18.,19.,20.,21.,22.,23.,24.,25.,26.,27.,28.,29.,30.,31.,32.,33.,34.,35.,36.,37.] {walk(&b,&mut s,&a,p,w)}(b,s,p,a)}
#[test]fn room40_to_room41_forward_chain_and_cast(){let(b,mut s,p,a)=reach_room37();walk(&b,&mut s,&a,p,38.);assert_eq!(s.current_room,38.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,204.));assert_eq!(cast(&s,WOLF),1);assert_eq!(cast(&s,BAT),1);assert_eq!(cast(&s,SLIME),4);assert_eq!(cast(&s,FIRESLIME),1);assert_eq!(cast(&s,BOULDER),474);assert_eq!(cast(&s,PLATFORM),3);assert_eq!(cast(&s,SPIKES),50);assert_eq!(cast(&s,COIN),35);assert_eq!(cast(&s,PICKUPFLARE),1);assert_eq!(cast(&s,BOW),1);assert!(doors(&s).contains(&(39.,128.,204.)));assert!(doors(&s).contains(&(37.,1888.,524.)))}
#[test]fn room41_to_room42_is_asset_exact(){let(b,mut s,p,a)=reach_room37();walk(&b,&mut s,&a,p,38.);walk(&b,&mut s,&a,p,39.);assert_eq!(s.current_room,39.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,204.));assert_eq!(cast(&s,KNIFEBANDIT),1);assert_eq!(cast(&s,ZOMBIE),3);assert_eq!(cast(&s,ENEMY2),1);assert_eq!(cast(&s,GHOST),4);assert_eq!(cast(&s,SLIME),2);assert_eq!(cast(&s,FIRESLIME),2);assert_eq!(cast(&s,BOULDER),317);assert_eq!(cast(&s,PLATFORM),4);assert_eq!(cast(&s,COIN),17);assert_eq!(cast(&s,GEM),1);assert_eq!(cast(&s,CHEST),5);assert_eq!(cast(&s,LLOYD),1);assert_eq!(cast(&s,BOULDERBLOCK),5);assert_eq!(cast(&s,TRIGGERINTRO),1);assert!(doors(&s).contains(&(38.,1920.,204.)));assert!(doors(&s).contains(&(40.,160.,1164.)))}
#[test]fn room42_to_room43_door_chain_continues(){let(b,mut s,p,a)=reach_room37();walk(&b,&mut s,&a,p,38.);walk(&b,&mut s,&a,p,39.);walk(&b,&mut s,&a,p,40.);assert_eq!(s.current_room,40.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(160.,1164.));assert!(doors(&s).contains(&(41.,128.,204.)));assert!(doors(&s).contains(&(39.,1888.,1164.)))}
