//! room76-79 (asset rooms 75-78) post-Boss3 branch chain, fifteenth
//! segment. gml names via room_bindings: asset75=room76, asset76=room77,
//! asset77=room78, asset78=room79 (offset +1, same rule as segments
//! thirteen/fourteen; see room68-71-branch.md). Door CODEs 954-961 verified
//! at bytecode level; casts and landing pins probed live on this host first.
use callys_asset::GameDroidAsset;
use callys_core::code_vm::{load_bundle_from_file, Host};
use callys_core::ir_scene::{Scene, SpriteBounds};
use std::path::Path;
const P:i32=0;const W:i32=69;const WALL4:i32=4;const WALL5:i32=5;const BOULDER:i32=6;const PLATFORM:i32=7;const KNIFE:i32=15;const SHOOTER1:i32=16;const SKELETON:i32=17;const ZOMBIE:i32=19;const SHOOTER2:i32=20;const HULK:i32=21;const ENEMY2:i32=22;const GHOST:i32=24;const BAT:i32=31;const FIRE:i32=33;const COIN:i32=58;const PICKUPFLARE:i32=70;const LASER:i32=80;const CHEST:i32=100;const BBLOCK:i32=156;const ICEBLOCK:i32=159;
fn setup()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let r=Path::new(env!("CARGO_MANIFEST_DIR"));let a=GameDroidAsset::parse(r.join("../../assets/game.droid")).unwrap();let mut b=load_bundle_from_file(&r.join("src/generated/full_ir.json")).unwrap();b.string_table=a.string_table.clone();let mut s=Scene::default();s.init_bundle(&b);s.init_fresh_start_globals();for(sid,sp)in&a.sprites{s.sprite_bounds.insert(*sid as i32,SpriteBounds{width:sp.width as f64,height:sp.height as f64,origin_x:sp.origin_x as f64,origin_y:sp.origin_y as f64,frames:sp.tpag_indices.len().max(1)as f64});}s.load_room_from_data(&b,0,&a.rooms[0]).unwrap();s.transition_to_room(&b,1,&a.rooms[1]).unwrap();s.view_positions.insert(0,(0.,0.));let p=s.instances.iter().find(|(_,i)|i.object==P&&i.alive).map(|(id,_)|*id).unwrap();(b,s,p,a)}
fn walk(b:&callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,w:f64){let id=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive&&i.active).find(|(_,i)|i.fields.get("warproom").copied()==Some(w)).map(|(id,_)|*id).unwrap();let(x,y)=(s.instances[&id].fields["x"],s.instances[&id].fields["y"]);s.write(p,-1,"x",None,x).unwrap();s.write(p,-1,"y",None,y).unwrap();for _ in 0..3{s.tick(b).unwrap();if s.target_room_warp.is_some(){break}}let t=s.target_room_warp.take().unwrap();s.transition_to_room(b,t,&a.rooms[t]).unwrap()}
fn cast(s:&Scene,o:i32)->usize{s.instances.iter().filter(|(_,i)|i.object==o&&i.alive).count()}fn doors(s:&Scene)->Vec<(f64,f64,f64)>{s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).map(|(_,i)|(i.fields["warproom"],i.fields["warpx"],i.fields["warpy"])).collect()}
fn assert_all_doors_unlocked(s:&Scene,room:f64){let live:Vec<_>=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).collect();assert_eq!(live.len(),2,"exactly two warp pins in asset room {room}");for (_,i) in &live{assert_eq!(i.fields.get("unlocked").copied(),Some(1.),"CODE 95x-96x pins unlocked=1 on both doors of asset room {room}");}}
fn reach74()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let(b,mut s,p,a)=setup();s.transition_to_room(&b,4,&a.rooms[4]).unwrap();for w in (5i32..=74).filter(|x|*x!=6).map(|x|x as f64){walk(&b,&mut s,&a,p,w)}(b,s,p,a)}
#[test]fn room76_platform_vault_is_asset_exact(){let(b,mut s,p,a)=reach74();walk(&b,&mut s,&a,p,75.);assert_eq!(s.current_room,75.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(672.,684.),"CODE 953 landing");assert_eq!(cast(&s,WALL4),77);assert_eq!(cast(&s,WALL5),652,"wall_2-densest room of the whole branch");assert_eq!(cast(&s,BOULDER),255);assert_eq!(cast(&s,PLATFORM),30,"platform-densest room, a vertical climbing vault");assert_eq!(cast(&s,KNIFE),1);assert_eq!(cast(&s,SHOOTER2),1);assert_eq!(cast(&s,HULK),3);assert_eq!(cast(&s,COIN),21);assert_eq!(cast(&s,CHEST),7,"seven-chest hoard behind the climb");assert_eq!(cast(&s,ICEBLOCK),0);assert!(doors(&s).contains(&(74.,320.,1420.)),"CODE 955 return pin");assert!(doors(&s).contains(&(76.,128.,204.)),"CODE 954 forward pin");assert_all_doors_unlocked(&s,75.);}
#[test]fn room77_laser_pickup_shrine(){let(b,mut s,p,a)=reach74();walk(&b,&mut s,&a,p,75.);walk(&b,&mut s,&a,p,76.);assert_eq!(s.current_room,76.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,204.),"CODE 954 landing");assert_eq!(cast(&s,WALL4),228);assert_eq!(cast(&s,WALL5),238);assert_eq!(cast(&s,BOULDER),93);assert_eq!(cast(&s,GHOST),6,"ghost-densest room of the branch");assert_eq!(cast(&s,COIN),10);assert_eq!(cast(&s,ICEBLOCK),4);assert_eq!(cast(&s,PICKUPFLARE),1);assert_eq!(cast(&s,LASER),1,"obj_laser(80) weapon pickup, first of the branch");assert_eq!(cast(&s,CHEST),0,"no treasure in the shrine");assert!(doors(&s).contains(&(75.,1344.,1100.)),"CODE 956 return pin");assert!(doors(&s).contains(&(77.,128.,172.)),"CODE 957 forward pin");assert_all_doors_unlocked(&s,76.);}
#[test]fn room78_crypt_mixed_pack(){let(b,mut s,p,a)=reach74();walk(&b,&mut s,&a,p,75.);walk(&b,&mut s,&a,p,76.);walk(&b,&mut s,&a,p,77.);assert_eq!(s.current_room,77.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,172.),"CODE 957 landing");assert_eq!(cast(&s,WALL4),210);assert_eq!(cast(&s,WALL5),254);assert_eq!(cast(&s,BOULDER),291);assert_eq!(cast(&s,PLATFORM),4);assert_eq!(cast(&s,KNIFE),2);assert_eq!(cast(&s,SHOOTER1),1);assert_eq!(cast(&s,SKELETON),2);assert_eq!(cast(&s,ZOMBIE),3);assert_eq!(cast(&s,ENEMY2),1);assert_eq!(cast(&s,BAT),1);assert_eq!(cast(&s,FIRE),2);assert_eq!(cast(&s,COIN),31);assert_eq!(cast(&s,CHEST),1);assert!(doors(&s).contains(&(76.,1920.,108.)),"CODE 958 return pin");assert!(doors(&s).contains(&(78.,128.,108.)),"CODE 959 forward pin");assert_all_doors_unlocked(&s,77.);}
#[test]fn room79_hoard_room_and_full_return_chain(){let(b,mut s,p,a)=reach74();walk(&b,&mut s,&a,p,75.);walk(&b,&mut s,&a,p,76.);walk(&b,&mut s,&a,p,77.);walk(&b,&mut s,&a,p,78.);assert_eq!(s.current_room,78.,"asset78 = gml room79 (+1)");assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,108.),"CODE 959 landing");assert_eq!(cast(&s,WALL4),211);assert_eq!(cast(&s,WALL5),201);assert_eq!(cast(&s,BOULDER),119);assert_eq!(cast(&s,ENEMY2),3);assert_eq!(cast(&s,GHOST),4);assert_eq!(cast(&s,BAT),5);assert_eq!(cast(&s,COIN),25);assert_eq!(cast(&s,CHEST),7,"another seven-chest hoard (asset75 had one too)");assert_eq!(cast(&s,BBLOCK),2,"sixth boulderblock room (rocket payoff)");assert_eq!(cast(&s,ICEBLOCK),0);assert_eq!(cast(&s,LASER),0,"the laser pickup is a single shrine");assert!(doors(&s).contains(&(77.,1152.,204.)),"CODE 960 return pin");assert!(doors(&s).contains(&(79.,128.,204.)),"CODE 961 forward pin continues to asset79");assert_all_doors_unlocked(&s,78.);
walk(&b,&mut s,&a,p,77.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1152.,204.),"CODE 960 landing back in asset77");walk(&b,&mut s,&a,p,76.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1920.,108.),"CODE 958 landing back in asset76");walk(&b,&mut s,&a,p,75.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1344.,1100.),"CODE 956 landing back in asset75");walk(&b,&mut s,&a,p,74.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(320.,1420.),"CODE 955 landing back in asset74");assert_eq!(s.current_room,74.);}