//! room60-63 (asset rooms 58-61) post-Boss3 branch chain, eleventh segment.
//! gml names via room_bindings: asset58=room60, asset59=room61, asset60=room62,
//! asset61=room63 (offset +2; see room68-71-branch.md for the corrected rule).
//! Door CODEs 920-927 verified
//! at bytecode level; casts and landing pins probed live on this host first.
use callys_asset::GameDroidAsset;
use callys_core::code_vm::{load_bundle_from_file, Host};
use callys_core::ir_scene::{Scene, SpriteBounds};
use std::path::Path;
const P:i32=0;const W:i32=69;const WALL4:i32=4;const WALL5:i32=5;const BOULDER:i32=6;const PLATFORM:i32=7;const SPIKE:i32=8;const WATERSURFACE:i32=9;const WATERFILL:i32=10;const ENEMY:i32=14;const KNIFE:i32=15;const FIREHULK:i32=18;const ZOMBIE:i32=19;const HULK:i32=21;const ENEMY2:i32=22;const WOLF:i32=23;const GHOST:i32=24;const BAT:i32=31;const SLIME:i32=32;const FIRE:i32=33;const COIN:i32=58;const CHEST:i32=100;const BBLOCK:i32=156;const ICEBLOCK:i32=159;
fn setup()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let r=Path::new(env!("CARGO_MANIFEST_DIR"));let a=GameDroidAsset::parse(r.join("../../assets/game.droid")).unwrap();let mut b=load_bundle_from_file(&r.join("src/generated/full_ir.json")).unwrap();b.string_table=a.string_table.clone();let mut s=Scene::default();s.init_bundle(&b);s.init_fresh_start_globals();for(sid,sp)in&a.sprites{s.sprite_bounds.insert(*sid as i32,SpriteBounds{width:sp.width as f64,height:sp.height as f64,origin_x:sp.origin_x as f64,origin_y:sp.origin_y as f64,frames:sp.tpag_indices.len().max(1)as f64});}s.load_room_from_data(&b,0,&a.rooms[0]).unwrap();s.transition_to_room(&b,1,&a.rooms[1]).unwrap();s.view_positions.insert(0,(0.,0.));let p=s.instances.iter().find(|(_,i)|i.object==P&&i.alive).map(|(id,_)|*id).unwrap();(b,s,p,a)}
fn walk(b:&callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,w:f64){let id=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive&&i.active).find(|(_,i)|i.fields.get("warproom").copied()==Some(w)).map(|(id,_)|*id).unwrap();let(x,y)=(s.instances[&id].fields["x"],s.instances[&id].fields["y"]);s.write(p,-1,"x",None,x).unwrap();s.write(p,-1,"y",None,y).unwrap();for _ in 0..3{s.tick(b).unwrap();if s.target_room_warp.is_some(){break}}let t=s.target_room_warp.take().unwrap();s.transition_to_room(b,t,&a.rooms[t]).unwrap()}
fn cast(s:&Scene,o:i32)->usize{s.instances.iter().filter(|(_,i)|i.object==o&&i.alive).count()}fn doors(s:&Scene)->Vec<(f64,f64,f64)>{s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).map(|(_,i)|(i.fields["warproom"],i.fields["warpx"],i.fields["warpy"])).collect()}
fn assert_all_doors_unlocked(s:&Scene,room:f64){let live:Vec<_>=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive).collect();assert_eq!(live.len(),2,"exactly two warp pins in asset room {room}");for (_,i) in &live{assert_eq!(i.fields.get("unlocked").copied(),Some(1.),"CODE 92x pins unlocked=1 on both doors of asset room {room}");}}
fn reach57()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let(b,mut s,p,a)=setup();s.transition_to_room(&b,4,&a.rooms[4]).unwrap();for w in (5i32..=57).filter(|x|*x!=6).map(|x|x as f64){walk(&b,&mut s,&a,p,w)}(b,s,p,a)}
#[test]fn room60_iceblock_corridor_is_asset_exact(){let(b,mut s,p,a)=reach57();walk(&b,&mut s,&a,p,58.);assert_eq!(s.current_room,58.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,204.),"CODE 919 landing");assert_eq!(cast(&s,WALL4),225);assert_eq!(cast(&s,WALL5),187);assert_eq!(cast(&s,BOULDER),104);assert_eq!(cast(&s,FIREHULK),2);assert_eq!(cast(&s,ZOMBIE),2);assert_eq!(cast(&s,HULK),2);assert_eq!(cast(&s,BAT),2);assert_eq!(cast(&s,SLIME),1);assert_eq!(cast(&s,FIRE),1);assert_eq!(cast(&s,COIN),11);assert_eq!(cast(&s,ICEBLOCK),3);assert_eq!(cast(&s,CHEST),0,"no treasure in the corridor");assert_eq!(cast(&s,SPIKE),0);assert!(doors(&s).contains(&(57.,672.,364.)),"CODE 920 return pin");assert!(doors(&s).contains(&(59.,128.,204.)),"CODE 921 forward pin");assert_all_doors_unlocked(&s,58.);}
#[test]fn room61_spike_lake_is_asset_exact(){let(b,mut s,p,a)=reach57();walk(&b,&mut s,&a,p,58.);walk(&b,&mut s,&a,p,59.);assert_eq!(s.current_room,59.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,204.),"CODE 921 landing");assert_eq!(cast(&s,WALL4),141);assert_eq!(cast(&s,WALL5),105);assert_eq!(cast(&s,BOULDER),154);assert_eq!(cast(&s,SPIKE),59);assert_eq!(cast(&s,WATERSURFACE),18);assert_eq!(cast(&s,WATERFILL),5);assert_eq!(cast(&s,BAT),3);assert_eq!(cast(&s,COIN),15);assert_eq!(cast(&s,CHEST),2);assert_eq!(cast(&s,ICEBLOCK),2);assert_eq!(cast(&s,ENEMY),0,"bats are the only movers in the spike lake");assert_eq!(cast(&s,KNIFE),0);assert!(doors(&s).contains(&(58.,1888.,364.)),"CODE 922 return pin");assert!(doors(&s).contains(&(60.,128.,140.)),"CODE 923 forward pin");assert_all_doors_unlocked(&s,59.);}
#[test]fn room62_chest_stacks_and_boulderblocks(){let(b,mut s,p,a)=reach57();walk(&b,&mut s,&a,p,58.);walk(&b,&mut s,&a,p,59.);walk(&b,&mut s,&a,p,60.);assert_eq!(s.current_room,60.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,140.),"CODE 923 landing");assert_eq!(cast(&s,WALL4),163);assert_eq!(cast(&s,WALL5),192);assert_eq!(cast(&s,BOULDER),200);assert_eq!(cast(&s,PLATFORM),2);assert_eq!(cast(&s,ENEMY),1);assert_eq!(cast(&s,KNIFE),1);assert_eq!(cast(&s,HULK),1);assert_eq!(cast(&s,WOLF),1);assert_eq!(cast(&s,GHOST),1);assert_eq!(cast(&s,BAT),4);assert_eq!(cast(&s,FIRE),1);assert_eq!(cast(&s,COIN),18);assert_eq!(cast(&s,CHEST),5);assert_eq!(cast(&s,BBLOCK),3,"third boulderblock room of the branch");assert_eq!(cast(&s,ICEBLOCK),2);assert!(doors(&s).contains(&(59.,1920.,172.)),"CODE 924 return pin");assert!(doors(&s).contains(&(61.,128.,108.)),"CODE 925 forward pin");assert_all_doors_unlocked(&s,60.);}
#[test]fn room63_water_crossing_and_return_chain(){let(b,mut s,p,a)=reach57();walk(&b,&mut s,&a,p,58.);walk(&b,&mut s,&a,p,59.);walk(&b,&mut s,&a,p,60.);walk(&b,&mut s,&a,p,61.);assert_eq!(s.current_room,61.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(128.,108.),"CODE 925 landing");assert_eq!(cast(&s,WALL4),186);assert_eq!(cast(&s,WALL5),201);assert_eq!(cast(&s,BOULDER),179);assert_eq!(cast(&s,WATERSURFACE),47);assert_eq!(cast(&s,WATERFILL),1);assert_eq!(cast(&s,FIREHULK),1);assert_eq!(cast(&s,ENEMY2),1);assert_eq!(cast(&s,GHOST),2);assert_eq!(cast(&s,BAT),1);assert_eq!(cast(&s,SLIME),1);assert_eq!(cast(&s,FIRE),2);assert_eq!(cast(&s,COIN),34);assert_eq!(cast(&s,CHEST),0,"no treasure in the crossing");assert!(doors(&s).contains(&(60.,640.,1164.)),"CODE 926 return pin");assert!(doors(&s).contains(&(62.,1664.,620.)),"CODE 927 forward pin continues to asset62");assert_all_doors_unlocked(&s,61.);
walk(&b,&mut s,&a,p,60.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(640.,1164.),"CODE 926 landing back in asset60");walk(&b,&mut s,&a,p,59.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1920.,172.),"CODE 924 landing back in asset59");walk(&b,&mut s,&a,p,58.);assert_eq!((s.instances[&p].fields["x"],s.instances[&p].fields["y"]),(1888.,364.),"CODE 922 landing back in asset58");assert_eq!(s.current_room,58.);}
