//! Rocket launcher (75, CODE 390/391), ice gun (81, CODE 402/403) and spike gun
//! (72, CODE 384/385) pickups: same two-event shape as shotgun/rifle, beacon
//! offsets (x+8,y-20)/(x+4,y-18)/(x+8,y-12), self=1 exclusivity row, banner on
//! the pickup's own coordinates. Verified against full_ir.json bytecode.
use callys_asset::GameDroidAsset;
use callys_core::code_vm::{load_bundle_from_file, Host};
use callys_core::ir_scene::{Scene, SpriteBounds};
use std::path::Path;
const P:i32=0;const W:i32=69;const PICKUPFLARE:i32=70;const SPIKEGUN:i32=72;const ROCKET:i32=75;const ICEGUN:i32=81;const FOUNDWEAPON:i32=82;
const WEAPONS:[&str;12]=["pistol","shotgun","assaultrifle","rocket","laser","icegun","bladegun","flamethrower","bow","bombgun","boomerang","spikegun"];
fn setup()->(callys_core::code_vm::Bundle,Scene,i32,GameDroidAsset){let r=Path::new(env!("CARGO_MANIFEST_DIR"));let a=GameDroidAsset::parse(r.join("../../assets/game.droid")).unwrap();let mut b=load_bundle_from_file(&r.join("src/generated/full_ir.json")).unwrap();b.string_table=a.string_table.clone();let mut s=Scene::default();s.init_bundle(&b);s.init_fresh_start_globals();for(sid,sp)in&a.sprites{s.sprite_bounds.insert(*sid as i32,SpriteBounds{width:sp.width as f64,height:sp.height as f64,origin_x:sp.origin_x as f64,origin_y:sp.origin_y as f64,frames:sp.tpag_indices.len().max(1)as f64});}s.load_room_from_data(&b,0,&a.rooms[0]).unwrap();s.transition_to_room(&b,1,&a.rooms[1]).unwrap();s.view_positions.insert(0,(0.,0.));let p=s.instances.iter().find(|(_,i)|i.object==P&&i.alive).map(|(id,_)|*id).unwrap();(b,s,p,a)}
fn walk(b:&callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,w:f64){let id=s.instances.iter().filter(|(_,i)|i.object==W&&i.alive&&i.active).find(|(_,i)|i.fields.get("warproom").copied()==Some(w)).map(|(id,_)|*id).unwrap();let(x,y)=(s.instances[&id].fields["x"],s.instances[&id].fields["y"]);s.write(p,-1,"x",None,x).unwrap();s.write(p,-1,"y",None,y).unwrap();for _ in 0..3{s.tick(b).unwrap();if s.target_room_warp.is_some(){break}}let t=s.target_room_warp.take().unwrap();s.transition_to_room(b,t,&a.rooms[t]).unwrap()}
fn cast(s:&Scene,o:i32)->Vec<i32>{s.instances.iter().filter(|(_,i)|i.object==o&&i.alive).map(|(id,_)|*id).collect()}
fn active(s:&Scene)->Vec<String>{WEAPONS.iter().filter(|w|s.globals.get(**w).copied()==Some(1.)).map(|w|(*w).to_string()).collect()}
fn reach(b:&mut callys_core::code_vm::Bundle,s:&mut Scene,a:&GameDroidAsset,p:i32,target:f64){s.transition_to_room(b,4,&a.rooms[4]).unwrap();for w in (5i32..=target as i32).filter(|x|*x!=6).map(|x|x as f64){walk(b,s,a,p,w)}}
fn collect(b:&callys_core::code_vm::Bundle,s:&mut Scene,p:i32,pickup:i32){let(px,py)=(s.instances[&pickup].fields["x"],s.instances[&pickup].fields["y"]);s.write(p,-1,"x",None,px).unwrap();s.write(p,-1,"y",None,py).unwrap();for _ in 0..4{s.tick(b).unwrap();if !s.instances[&pickup].alive{break}}assert!(!s.instances[&pickup].alive,"the Step code destroys the pickup on contact")}
#[test]fn the_rocket_launcher_pickup_flips_the_weapon_row(){let(mut b,mut s,p,a)=setup();reach(&mut b,&mut s,&a,p,45.);assert_eq!(s.current_room,45.);let gun=*cast(&s,ROCKET).first().expect("one rocket launcher in asset room 45");let flare=cast(&s,PICKUPFLARE);assert_eq!(flare.len(),1,"CODE 390 spawns exactly one beacon");assert_eq!(s.instances[&flare[0]].fields["x"],s.instances[&gun].fields["x"]+8.,"beacon x offset +8");assert_eq!(s.instances[&flare[0]].fields["y"],s.instances[&gun].fields["y"]-20.,"beacon y offset -20");let(sx,sy)=(s.instances[&gun].fields["x"],s.instances[&gun].fields["y"]);assert_eq!(active(&s),vec!["pistol".to_string()]);collect(&b,&mut s,p,gun);assert_eq!(s.globals["rocketbought"],1.,"CODE 391 raises rocketbought");assert_eq!(active(&s),vec!["rocket".to_string()],"exactly the rocket stays active");let banner=*cast(&s,FOUNDWEAPON).first().expect("banner");assert_eq!((s.instances[&banner].fields["x"],s.instances[&banner].fields["y"]),(sx,sy),"banner spawns on the pickup coordinates")}
#[test]fn the_ice_gun_pickup_flips_the_weapon_row(){let(mut b,mut s,p,a)=setup();reach(&mut b,&mut s,&a,p,51.);assert_eq!(s.current_room,51.);let gun=*cast(&s,ICEGUN).first().expect("one ice gun in asset room 51");let flare=cast(&s,PICKUPFLARE);assert_eq!(flare.len(),1,"CODE 402 spawns exactly one beacon");assert_eq!(s.instances[&flare[0]].fields["x"],s.instances[&gun].fields["x"]+4.,"beacon x offset +4");assert_eq!(s.instances[&flare[0]].fields["y"],s.instances[&gun].fields["y"]-18.,"beacon y offset -18");collect(&b,&mut s,p,gun);assert_eq!(s.globals["icegunbought"],1.,"CODE 403 raises icegunbought");assert_eq!(active(&s),vec!["icegun".to_string()],"exactly the ice gun stays active")}
#[test]fn a_bought_ice_gun_vanishes_on_room_reentry(){let(mut b,mut s,p,a)=setup();s.globals.insert("icegunbought".to_string(),1.0);reach(&mut b,&mut s,&a,p,51.);assert_eq!(s.current_room,51.);assert!(cast(&s,ICEGUN).is_empty(),"CODE 402 destroys the gun before leaving a beacon");assert!(cast(&s,PICKUPFLARE).is_empty(),"no beacon either for an owned weapon");assert_eq!(active(&s),vec!["pistol".to_string()],"the destroy path must not flip the weapon row")}
#[test]fn the_spike_gun_pickup_flips_the_weapon_row(){let(mut b,mut s,p,a)=setup();reach(&mut b,&mut s,&a,p,53.);assert_eq!(s.current_room,53.);let gun=*cast(&s,SPIKEGUN).first().expect("one spike gun in asset room 53");let flare=cast(&s,PICKUPFLARE);assert_eq!(flare.len(),1,"CODE 384 spawns exactly one beacon");assert_eq!(s.instances[&flare[0]].fields["x"],s.instances[&gun].fields["x"]+8.,"beacon x offset +8");assert_eq!(s.instances[&flare[0]].fields["y"],s.instances[&gun].fields["y"]-12.,"beacon y offset -12");collect(&b,&mut s,p,gun);assert_eq!(s.globals["spikegunbought"],1.,"CODE 385 raises spikegunbought");assert_eq!(active(&s),vec!["spikegun".to_string()],"exactly the spike gun stays active")}

