#!/usr/bin/env python3
"""Object evidence matrix (E2): one row per OBJT object in `full_ir.json`,
aggregating the per-CODE axes the census already tracks into a per-object
audit view.

Columns (all computed from live artifacts - nothing hand-copied):

- `ev`: event entries the bundle records for the object.
- `codes`: CODE bodies owned by those events.
- `c` / `t` / `s`: bodies cited (by id or by object name) in contracts / tests
  / src. `e`: env_classified (with-pending sites). `u`: uncited (structural or
  unclassified). These are the census tiers verbatim, bucketed for display.
- `executed`: bodies entered by the full-suite execution ledger / owned total.
- `pending`: `environment_ops_pending` sites summed over the object's bodies.

Boundary: this is aggregation only. Execution is evidence that the body ran
under a test, NOT behavioural equivalence, and the tier labels carry the
census's own meaning (see `semantic-coverage.md`). The `stack_semantics` /
`behavior_verified` columns of the old CFG ledger are frozen 2026-09 data and
are deliberately NOT read here.

Usage:  python3 scripts/audit_object_matrix.py [--root .] [--ledger P]
        [--exec-trace P ...] [--bundle P] [--md OUT]
"""
from __future__ import annotations

import argparse
import collections
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT_DEFAULT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import audit_semantic_coverage as asc  # noqa: E402

DEDUP_DEFAULT = "reconstruction/live-mem/trace/cally-code-trace-full-dedup.txt"
BUNDLE_DEFAULT = "crates/core/src/generated/full_ir.json"
OUT_DEFAULT = "reconstruction/contracts/object-matrix.md"
MARKER = "<!-- Generated by `scripts/audit_object_matrix.py`. Do not hand-edit. -->"

BUCKET_OF = {
    "cited_contract": "c",
    "object_cited_contract": "c",
    "cited_test": "t",
    "object_cited_test": "t",
    "cited_src": "s",
    "object_cited_src": "s",
    "env_classified": "e",
    "structural": "u",
    "unclassified": "u",
    "cited_id_not_in_ledger": "u",
}
BUCKET_ORDER = ("c", "t", "s", "e", "u")


def load_bundle(path: str) -> list[dict]:
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    return data["objects"]


def build_matrix(census: dict, bundle_objects: list[dict]) -> dict:
    codes: dict[int, dict] = census["codes"]
    rows = []
    seen: set[int] = set()
    unlisted = 0
    for obj in bundle_objects:
        own: list[int] = []
        for event in obj.get("events", []):
            for cid in event.get("codes", []):
                own.append(int(cid))
        own = sorted(set(own))
        buckets = collections.Counter()
        executed = 0
        pending = 0
        unexecuted: list[int] = []
        for cid in own:
            seen.add(cid)
            entry = codes.get(cid)
            if entry is None:
                unlisted += 1
                buckets["u"] += 1
                unexecuted.append(cid)
                continue
            buckets[BUCKET_OF.get(entry["tier"], "u")] += 1
            if entry["executed"]:
                executed += 1
            else:
                unexecuted.append(cid)
            pending += entry["environment_ops_pending"]
        rows.append({
            "object": obj["name"],
            "id": obj["id"],
            "events": len(obj.get("events", [])),
            "codes": len(own),
            "buckets": {b: buckets.get(b, 0) for b in BUCKET_ORDER},
            "executed": executed,
            "unexecuted": unexecuted,
            "pending": pending,
        })

    # Census codes nobody owns via an object event: RoomCC / Script / other.
    containers: dict[str, dict] = {}
    for cid, entry in codes.items():
        if cid in seen:
            continue
        kind = asc.name_kind(entry["name"]) if entry["name"] else "other"
        bucket = containers.setdefault(kind, {"codes": 0, "executed": 0,
                                              "buckets": collections.Counter()})
        bucket["codes"] += 1
        bucket["buckets"][BUCKET_OF.get(entry["tier"], "u")] += 1
        if entry["executed"]:
            bucket["executed"] += 1

    totals = {
        "objects": len(rows),
        "object_codes": sum(r["codes"] for r in rows),
        "executed": sum(r["executed"] for r in rows),
        "objects_with_unexecuted": sum(1 for r in rows if r["unexecuted"]),
        "total_codes": len(codes),
        "unlisted": unlisted,
    }
    return {"rows": rows, "containers": containers, "totals": totals}


def _bucket_mix(buckets: dict) -> str:
    return " ".join(f"{b}:{buckets[b]}" for b in BUCKET_ORDER if buckets[b])


def render_markdown(matrix: dict) -> str:
    rows = matrix["rows"]
    totals = matrix["totals"]
    lines = []
    lines.append("# Object evidence matrix (E2)")
    lines.append("")
    lines.append(MARKER)
    lines.append("")
    lines.append("One row per OBJT object in `full_ir.json`, aggregating the per-CODE")
    lines.append("axes of `semantic-coverage.md` into a per-object audit view. Column")
    lines.append("meaning and boundaries are in the generator's docstring; the short")
    lines.append("form: `c`/`t`/`s` = cited in contracts/tests/src, `e` = env_classified,")
    lines.append("`u` = uncited, `executed` = entered by the full-suite ledger,")
    lines.append("`pending` = with-pending environment sites. Execution is evidence a body")
    lines.append("ran, not behavioural equivalence; the old CFG ledger's semantics/behaviour")
    lines.append("columns are frozen 2026-09 data and are not read here.")
    lines.append("")
    lines.append("## Totals")
    lines.append("")
    lines.append(f"- objects: {totals['objects']}")
    lines.append(f"- object-owned CODE bodies: {totals['object_codes']} "
                 f"(of {totals['total_codes']} total in the merged census)")
    lines.append(f"- executed: {totals['executed']}/{totals['object_codes']} object-owned")
    lines.append(f"- objects with any unexecuted body: {totals['objects_with_unexecuted']}")
    lines.append("")
    lines.append("## Still unexecuted, by object (weakest first)")
    lines.append("")
    weak = sorted((r for r in rows if r["unexecuted"]),
                  key=lambda r: (-len(r["unexecuted"]), r["object"]))
    if weak:
        lines.append("| object | unexecuted | ids |")
        lines.append("| --- | --- | --- |")
        for r in weak:
            lines.append(f"| `{r['object']}` | {len(r['unexecuted'])} | "
                         f"{', '.join(str(i) for i in r['unexecuted'])} |")
    else:
        lines.append("None - every object-owned body has been executed.")
    lines.append("")
    lines.append("## Matrix")
    lines.append("")
    lines.append("| object | id | ev | codes | c | t | s | e | u | executed | pending |")
    lines.append("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    for r in sorted(rows, key=lambda r: r["object"]):
        b = r["buckets"]
        lines.append(f"| `{r['object']}` | {r['id']} | {r['events']} | {r['codes']} | "
                     f"{b['c']} | {b['t']} | {b['s']} | {b['e']} | {b['u']} | "
                     f"{r['executed']}/{r['codes']} | {r['pending']} |")
    lines.append("")
    lines.append("## Room / script / other containers")
    lines.append("")
    lines.append("Codes not owned via an object event. Room creation code is asserted at")
    lines.append("the room level by the room-chain suites, which is why those bodies read")
    lines.append("`u` in the census but still execute.")
    lines.append("")
    lines.append("| container | codes | tier mix | executed |")
    lines.append("| --- | --- | --- | --- |")
    for kind in sorted(matrix["containers"]):
        d = matrix["containers"][kind]
        lines.append(f"| `{kind}` | {d['codes']} | {_bucket_mix(d['buckets'])} | "
                     f"{d['executed']}/{d['codes']} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=ROOT_DEFAULT)
    ap.add_argument("--ledger", default=None)
    ap.add_argument("--exec-trace", action="append", default=None)
    ap.add_argument("--bundle", default=None)
    ap.add_argument("--md", default=None)
    args = ap.parse_args()

    root = os.path.abspath(args.root)
    ledger = args.ledger or asc.find_ledger(None)
    traces = args.exec_trace or [os.path.join(root, DEDUP_DEFAULT)]
    bundle_path = args.bundle or os.path.join(root, BUNDLE_DEFAULT)
    out = args.md or os.path.join(root, OUT_DEFAULT)

    census = asc.build_census(root, ledger, traces)
    objects = load_bundle(bundle_path)
    matrix = build_matrix(census, objects)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(render_markdown(matrix))
    t = matrix["totals"]
    print(f"objects {t['objects']} | object codes {t['object_codes']} "
          f"| executed {t['executed']}/{t['object_codes']} "
          f"| objects with unexecuted {t['objects_with_unexecuted']} "
          f"| unlisted {t['unlisted']}")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
